// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAFEe2B8k2ToQCqJTFcx2Bwj0cF59SjLr4',
    appId: '1:259997376057:web:c5bba196c84b6e1438b7e8',
    messagingSenderId: '259997376057',
    projectId: 'my-chat-app-d75bb',
    authDomain: 'my-chat-app-d75bb.firebaseapp.com',
    storageBucket: 'my-chat-app-d75bb.appspot.com',
    measurementId: 'G-RRQ97KC1QQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC-_e2VRTXpGutLou0nUIlNDIx7pDPBxAs',
    appId: '1:259997376057:android:fcfc2f4bfef27d3a38b7e8',
    messagingSenderId: '259997376057',
    projectId: 'my-chat-app-d75bb',
    storageBucket: 'my-chat-app-d75bb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBD8HrgiRgySzqymU6bzEOcHCP80-oZIJw',
    appId: '1:259997376057:ios:1dd62adc0333a92538b7e8',
    messagingSenderId: '259997376057',
    projectId: 'my-chat-app-d75bb',
    storageBucket: 'my-chat-app-d75bb.appspot.com',
    iosBundleId: 'com.example.myChat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBD8HrgiRgySzqymU6bzEOcHCP80-oZIJw',
    appId: '1:259997376057:ios:1dd62adc0333a92538b7e8',
    messagingSenderId: '259997376057',
    projectId: 'my-chat-app-d75bb',
    storageBucket: 'my-chat-app-d75bb.appspot.com',
    iosBundleId: 'com.example.myChat',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAFEe2B8k2ToQCqJTFcx2Bwj0cF59SjLr4',
    appId: '1:259997376057:web:93b3a90e6fe8055d38b7e8',
    messagingSenderId: '259997376057',
    projectId: 'my-chat-app-d75bb',
    authDomain: 'my-chat-app-d75bb.firebaseapp.com',
    storageBucket: 'my-chat-app-d75bb.appspot.com',
    measurementId: 'G-YGGT8726FS',
  );
}
